"""What the Delta Builder offers: fields, capabilities, presets and branding.

delta is a **fixed-shape** host, and that shapes this file more than anything
else. It is a maths e-learning platform: the LMS core (courses, tasks, skills,
notes) is what delta *is*, so none of it is a toggle. What varies is the
surrounding capabilities — the authoring editors, the library, subscriptions,
video playback, social sign-in — plus the ordinary deployment surface (ports,
TLS, target, database, admin).

Two rules govern the Features tab, and both exist so a generated config cannot
describe a broken host:

* **Capabilities are whole.** "Authoring tools" installs the editor base, memo,
  cyprian and primula together, because cyprian imports memo's sanitisers and
  raises ``cyprian.E001`` without it, and both build their file views on
  ``toto.editor``. Ticking three of the four is not a configuration anyone wants
  and not one this builder can produce.
* **Anything that cannot be switched off is not offered.** The LMS core is
  welded by foreign keys (academy → quizzes/competence/palimpsest), and
  ``toto.quota`` is imported unguarded by the vendored vault, so a host without
  it does not start. Neither appears here as a tick that would lie.

Every flag is **subtractive** — default on, written as ``"0"`` only when you
untick it — so a config that names none of them builds the delta that has always
shipped, and the two profiles in ``delta/deploy/configs/`` keep meaning exactly
what they meant before the flags existed.

Deliberately NOT offered: a Package tab (delta's deploy.py fork has no payload
manifest and the repo ships no ``run.sh``/``issue_letsencrypt.sh``), a
``--dry-run`` push (the fork's argparse rejects it), and ``server: asgi``
(delta is WSGI — it has no ASGI entry point and no websocket consumers).
"""

from __future__ import annotations

from pathlib import Path

from app import Capability, Field, HostSpec, Preset, derive_config
from validation import Issue, WARNING, get_path

HOST = "delta"

HEADER = """\
Generated by the Delta Builder (tools/) — review before deploying.

Bring it up with:
  python delta/scripts/deploy.py delta/deploy/configs/<this file> up --smart
Validate without touching anything:
  ... <this file> validate

delta is an e-learning host: the course/task/skill core is always built, and the
capabilities below are what varies. Keys left out keep deploy.py's defaults."""


IDENTITY = (
    Field("deployment.name", "Stack name",
          hint="The compose project name. Profiles that share it replace each "
               "other; a name of its own lets this stack run alongside them.",
          comment="compose project, .env and .compose dir name"),
    Field("deployment.project_dir", "Project dir", locked=True,
          hint="Fixed: the Django project this builder configures."),
    Field("server", "Server mode", kind="choice", choices=("wsgi",), locked=True,
          hint="delta is WSGI only — it ships no asgi.py and no websocket "
               "consumers, so there is nothing for an ASGI server to serve.",
          comment="gunicorn (wsgi)"),
    Field("env.PLATFORM_NAME", "Platform name", comment="shown in the UI"),
    Field("env.PLATFORM_DOMAIN", "Platform domain",
          hint="Also satisfies ssl.domain for Let's Encrypt."),
    Field("env.ALLOWED_HOSTS", "Allowed hosts",
          hint="Comma-separated. Django rejects any Host header not listed."),
    Field("env.CSRF_TRUSTED_ORIGINS", "CSRF trusted origins",
          hint="Comma-separated, with scheme: https://delta.example.com"),
    Field("env.LANGUAGE_CODE", "Language", kind="choice", choices=("pl", "en"),
          comment="delta's students are Polish-speaking by default"),
    Field("env.DB_PASSWORD", "Database password",
          hint="Required: postgres will not initialise without one, and the "
               "deploy tool never generates it. Postgres publishes no port, so "
               "this is not a network-facing secret.",
          comment="postgres password"),
    Field("admin.username", "Admin username",
          comment="the superuser init_platform creates"),
    Field("admin.person.display_name", "Admin display name",
          hint="Also links the admin's Person row, which the LMS resolves "
               "every learner through."),
)

NETWORK = (
    Field("nginx.http_port", "HTTP port", kind="int",
          comment="host port → container 80"),
    Field("nginx.https_port", "HTTPS port", kind="int",
          comment="host port → container 443"),
    Field("nginx.bind", "Bind address",
          hint="127.0.0.1 keeps a local stack off the network entirely. Leave "
               "empty to publish on every interface.",
          comment="127.0.0.1 = loopback only"),
    Field("ssl.mode", "TLS certificate", kind="choice",
          choices=("gervazy", "letsencrypt", "none"),
          hint="gervazy — a self-signed certificate generated on first boot. "
               "Browsers warn; fine for a laptop or a LAN.\n"
               "letsencrypt — a real, publicly trusted certificate. Needs a "
               "domain that resolves here and inbound port 80 during issuance.\n"
               "none — HTTP only; no TLS listener is published at all.",
          comment="gervazy = self-signed, no DNS needed"),
    Field("ssl.email", "Let's Encrypt email",
          hint="Required when the mode is letsencrypt; renewal warnings go here."),
    Field("target.type", "Deploy target", kind="choice",
          choices=("local", "ssh"),
          comment="local = this machine"),
    Field("target.host", "Target host",
          hint="IP or hostname — required for an ssh target."),
    Field("target.user", "Target user"),
    Field("target.key", "SSH key"),
    Field("target.remote_dir", "Remote dir"),
)

TABS = (
    ("Identity", IDENTITY),
    ("Network", NETWORK),
)


CAPABILITIES = (
    Capability("geo", "Maps and geography",
               "Geometry columns for addresses and places (PostGIS/GDAL). delta "
               "mounts no map pages — locations is installed as a model "
               "dependency of people and events — so this is really a database "
               "and image-size decision. Off gives a much lighter build with "
               "plain lat/lon floats.",
               flags=("BUILD_GEO",)),
    Capability("authoring", "Authoring tools",
               "The teacher's editors, as one piece: documents with real pages "
               "and a PDF export (cyprian), slide decks presented full-screen "
               "(memo), spreadsheets in the browser (primula, teachers-only), "
               "and the vault's generic file editor they all build on. A lesson's "
               "notes and presentation ARE files made here, so a course author "
               "wants all four or none — which is why it is one tick.",
               flags=("BUILD_AUTHORING",)),
    Capability("library", "Library",
               "The bibliography: books and articles curated by teachers, with "
               "its own back-office module and a tab in the student navigation.",
               flags=("BUILD_LIBRARY",)),
    Capability("subscriptions", "Subscriptions",
               "Paid access: plans, validity and discount codes, gating course "
               "enrolment. Off, every published course enrols freely — which is "
               "the right shape for a school that bills elsewhere, or not at all.",
               flags=("BUILD_SUBSCRIPTIONS",)),
    Capability("vod", "Video playback",
               "An in-browser player for the video and audio a lesson carries in "
               "the vault. No conversion, no worker, no ffmpeg — off, the files "
               "are still there and still download.",
               flags=("BUILD_VOD",)),
    Capability("social_login", "Sign in with Google / Facebook",
               "Adds the social sign-in buttons to the login page. Inert until "
               "the provider credentials are configured in the environment, so "
               "leaving it on costs nothing but keeps the option open.",
               flags=("BUILD_SOCIAL_LOGIN",)),
)


def _base(**over) -> dict:
    cfg = {
        "deployment": {"name": "delta", "project_dir": "delta"},
        "server": "wsgi",
        # delta's beat recomputes the recommendation similarity matrix nightly
        # and its vault work is queued, so the worker is part of the host rather
        # than an option — no capability turns it on or off.
        "services": {"celery": True},
        "target": {"type": "local"},
        "admin": {"username": "admin", "person": {"display_name": "Delta Admin"}},
        "env": {
            "DJANGO_ENV": "PROD",
            "DEBUG": "0",
            "RESET": "0",
            "FULL_INGRESS": "1",
            "LANGUAGE_CODE": "pl",
            "DB_NAME": "delta",
            "DB_USER": "delta",
            "DB_PASSWORD": "change_me_in_prod",
            "DB_PORT": "5432",
            "REDIS_CACHE_URL": "redis://redis:6379/1",
            "CELERY_BROKER_URL": "redis://redis:6379/0",
            "PLATFORM_NAME": "Delta",
            "PLATFORM_LOGO_PATH": "../data/img/delta.png",
            "EMAIL_BACKEND": "console",
        },
        "nginx": {"http_port": 8082, "https_port": 8443, "bind": "127.0.0.1"},
        "ssl": {"mode": "gervazy"},
        # No `cert` here on purpose: each preset supplies the whole block. An
        # empty list does not survive the YAML round-trip (it parses back as
        # None), so a half-filled cert cannot be a shared default.
    }
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(cfg.get(key), dict):
            cfg[key] = {**cfg[key], **value}
        else:
            cfg[key] = value
    return cfg


# (key, label, blurb, capabilities, config overrides)
PRESET_SPECS = (
    ("local", "Local — everything",
     "The whole platform on a laptop: every capability, self-signed TLS, demo "
     "data, and a database wiped and re-seeded on every start.",
     ("authoring", "library", "subscriptions", "vod", "social_login"),
     {"env": {"RESET": "1", "LOGIN_RETRY_COOLDOWN_SECONDS": "1",
              "PLATFORM_DOMAIN": "localhost",
              "ALLOWED_HOSTS": "localhost,127.0.0.1,web_delta,nginx,delta.local",
              "CSRF_TRUSTED_ORIGINS": "https://localhost,https://localhost:8443"},
      "cert": {"common_name": "localhost", "dns_names": ["localhost"],
               "ip_addresses": ["127.0.0.1"]},}),
    ("lean", "Local — course core only",
     "Courses, tasks, skills and notes, and nothing else: no authoring editors, "
     "no library, no subscriptions, no video. The fastest build, and the "
     "smallest surface to learn the platform on.",
     (),
     {"env": {"RESET": "1", "LOGIN_RETRY_COOLDOWN_SECONDS": "1",
              "PLATFORM_DOMAIN": "localhost",
              "ALLOWED_HOSTS": "localhost,127.0.0.1,web_delta,nginx,delta.local",
              "CSRF_TRUSTED_ORIGINS": "https://localhost,https://localhost:8443"},
      "cert": {"common_name": "localhost", "dns_names": ["localhost"],
               "ip_addresses": ["127.0.0.1"]},}),
    ("server", "Server + Let's Encrypt",
     "A real deployment: every capability, geometry on, a trusted certificate "
     "and no database reset. Fill in the domain, the target and the password "
     "before pushing.",
     ("geo", "authoring", "library", "subscriptions", "vod", "social_login"),
     {"ssl": {"mode": "letsencrypt", "email": ""},
      "target": {"type": "ssh", "host": "", "user": "root",
                 "remote_dir": "/opt/delta"},
      "nginx": {"http_port": 80, "https_port": 443, "bind": ""},
      # Placeholders rather than blanks, matching the shipped server template:
      # every one is meant to be edited, and a blank list would not round-trip.
      "env": {"PLATFORM_DOMAIN": "delta.example.com",
              "ALLOWED_HOSTS": "delta.example.com,web_delta,nginx,localhost,127.0.0.1",
              "CSRF_TRUSTED_ORIGINS": "https://delta.example.com"},
      "cert": {"common_name": "delta.example.com",
               "dns_names": ["delta.example.com"]}}),
)


def _preset_config(host_root: Path, caps: tuple[str, ...], over: dict) -> dict:
    cfg = _base(**over)
    env = cfg.setdefault("env", {})
    for cap in CAPABILITIES:
        # Subtractive flags: an untouched capability is ON, so only the ones the
        # preset leaves out are written — and written as an explicit "0", so the
        # file says what it decided rather than relying on a default.
        for flag in cap.flags:
            env[flag] = "1" if cap.key in caps else "0"
    return derive_config(CAPABILITIES, host_root, cfg)


def build_presets(host_root: Path) -> tuple[Preset, ...]:
    return tuple(
        Preset(key, label, blurb, _preset_config(host_root, caps, over))
        for key, label, blurb, caps, over in PRESET_SPECS
    )


def extra_checks(cfg: dict) -> list[Issue]:
    """delta-specific consistency the generic rules cannot know about."""
    found: list[Issue] = []

    env = cfg.get("env") or {}
    services = cfg.get("services") or {}

    # The worker is not optional on this host: beat recomputes the
    # recommendation matrix nightly, and without a broker every queued task
    # falls back to running inline in the request that asked for it.
    if not services.get("celery"):
        found.append(Issue(
            "services.celery",
            "delta runs a celery worker and beat — the recommendation matrix is "
            "recomputed nightly. Without them the schedule never fires and "
            "queued work runs inline in a web request instead.",
            WARNING))

    # RESET drops the schema on every container start. On anything but a local
    # target that is data loss, and deploy.py refuses it outright.
    if str(env.get("RESET", "")) == "1" and get_path(cfg, "target.type") not in ("local", None, ""):
        found.append(Issue(
            "env.RESET",
            "RESET=1 wipes the database on every start — never on a remote "
            "target. deploy.py refuses this combination.",
        ))

    # A trusted certificate needs a name to be issued for, and an address to be
    # reached at during the challenge.
    if get_path(cfg, "ssl.mode") == "letsencrypt":
        if not (get_path(cfg, "ssl.domain") or env.get("PLATFORM_DOMAIN")):
            found.append(Issue(
                "ssl.domain",
                "Let's Encrypt needs a domain that resolves to this host — set "
                "ssl.domain or PLATFORM_DOMAIN.",
            ))
        if not get_path(cfg, "ssl.email"):
            found.append(Issue(
                "ssl.email",
                "Let's Encrypt requires a contact address for renewal warnings.",
            ))

    # Console email accepts a password reset and then drops it on the floor.
    # Fine locally, a silent dead end on a server.
    if (env.get("EMAIL_BACKEND", "console") == "console"
            and get_path(cfg, "target.type") == "ssh"):
        found.append(Issue(
            "env.EMAIL_BACKEND",
            "the console backend prints mail to the container log instead of "
            "sending it, so 'Forgot password?' silently never arrives. Set "
            "EMAIL_BACKEND: smtp for a real deployment.",
            WARNING))

    # Demo content on a public server is a decision, not an accident.
    if (str(env.get("FULL_INGRESS", "")) == "1"
            and get_path(cfg, "target.type") == "ssh"):
        found.append(Issue(
            "env.FULL_INGRESS",
            "this seeds the demo maths course tree and sample subscription "
            "plans into a production database. Deliberate only if you want "
            "example content visible to real students.",
            WARNING))

    return found


def build_spec(host_root: Path) -> HostSpec:
    return HostSpec(
        host=HOST,
        app_name="Delta Builder",
        subtitle=(
            "Generate a deploy config for the delta host — the maths e-learning "
            "platform. The course core is always built; pick the capabilities "
            "around it, then save into the host's configs folder. The result is "
            "checked by deploy.py's own validator before it is written."
        ),
        host_root=host_root,
        icon=host_root / "data" / "img" / "delta.png",
        header=HEADER,
        tabs=TABS,
        presets=build_presets(host_root),
        capabilities=CAPABILITIES,
        extra_checks=extra_checks,
        default_filename="delta_custom.yaml",
    )
