# Generated by Django 4.2.23 on 2026-07-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_recommendationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_pl', models.CharField(blank=True, max_length=200)),
                ('headline_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_pl', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('invitation_pl', models.TextField(blank=True)),
                ('invitation_en', models.TextField(blank=True)),
                ('student_cta_pl', models.CharField(blank=True, max_length=80)),
                ('student_cta_en', models.CharField(blank=True, max_length=80)),
                ('teacher_cta_pl', models.CharField(blank=True, max_length=80)),
                ('teacher_cta_en', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welcome page copy',
                'verbose_name_plural': 'Welcome page copy',
            },
        ),
    ]
