# Generated by Django 4.2.23 on 2026-07-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_welcomecopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='academy.lesson')),
            ],
            options={
                'verbose_name': 'Lesson presentation',
                'verbose_name_plural': 'Lesson presentations',
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('subtitle', models.TextField(blank=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='academy.lessonpresentation')),
            ],
            options={
                'verbose_name': 'Presentation slide',
                'verbose_name_plural': 'Presentation slides',
                'ordering': ['order'],
            },
        ),
    ]
