# Generated by Django 4.2.23 on 2026-08-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_alter_vaultfile_file_type'),
        ('academy', '0006_presentation_becomes_a_memo_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notes_document',
            field=models.ForeignKey(blank=True, help_text='Optional authored lesson notes (a cyprian document from Vault).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_lesson_note_documents', to='vault.vaultfile'),
        ),
    ]
