# Generated by Django 4.2.23 on 2026-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizquestion_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='solution',
            field=models.TextField(blank=True, help_text='Rich worked solution (WYSIWYG). Shown after any practice submission and in the graded review. Falls back to the plain explanation when empty.'),
        ),
    ]
