# Generated by Django 4.2.23 on 2026-07-23 20:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(help_text="Machine code, e.g. 'academy_monthly'. Academy gating matches any plan whose code starts with 'academy'.", max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('interval_months', models.PositiveIntegerField(default=1, help_text='Access period length, in months.')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='List price for one interval (PLN).', max_digits=9)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Loyalty discount this plan unlocks (spec F-09: 5/10/15/20%).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'interval_months', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='people.person')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('percent', models.PositiveIntegerField(default=5)),
                ('is_used', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, help_text="Owner — a loyalty coupon shown in this person's profile. Blank = a generic promo code.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='people.person')),
                ('plan', models.ForeignKey(blank=True, help_text='Optional plan the coupon was granted for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
